name: Format checker

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master

jobs:
  check-format:
    name: Checks the format
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Check go fmt
      run: go fmt
    - name: Check go vet
      run: go vet
